### PR TITLE
pytraj: increase reference for DataSetList when using groupby

### PR DESCRIPTION
**Pull request by hainm**
why? make this object live longer to avoid segmentation fault when
calling `traj.search_hhonds().groupby("SER")`

Before: need to do this
dslist = traj.search_hhonds()
d0 = dslist.groupby("SER")

### CODE REVIEW

**Comment by swails** [comment]
Does this create a memory leak when you perform the "before" syntax?

**Comment by hainm** [comment]
@swails it's possible. I need to check the memory and might need to add 'counter' to check if user uses 'before' syntax or not.

**Comment by swails** [comment]
Maybe you're running into a race condition.  Does either `search_hbonds()` or `groupby` release the GIL?  If so, maybe the refcount of the DataSetList is going to zero while `groupby("SER")` is running and it gets garbage-collected while it's still being used?

In which case, all you've done is made sure that the result *never* gets freed...

Think of INCREF and DECREF as a malloc/free pair -- you need one DECREF for every INCREF you add.  The tricky part here is that several Python macros *include* either INCREF or DECREF, so you have to be aware of those.

All you did here was add an INCREF with no corresponding DECREF.  So if you weren't getting segfaults whenever you tried using this functionality (either with the "before" or "after" syntax), then you've most likely added a leak somewhere.

IMO, a leak is only a tiny bit better than a segfault.  And in this case, if the "before" syntax avoided both segfaults and leaks, the new behavior might be worse (if it does indeed always result in a leak).  H-bond datasets can be huge.

**Comment by swails** [comment]
Definitely a leak:

```Python
from __future__ import print_function
import unittest
import sys
from pytraj.base import *
from pytraj import adict
from pytraj import io as mdio
from pytraj.utils.check_and_assert import assert_almost_equal
from pytraj.decorators import no_test, test_if_having
import pytraj.common_actions as pyca


traj = mdio.iterload('./data/md1_prod.Tc5b.x', './data/Tc5b.top')

d = pyca.search_hbonds(traj)

sys.getrefcount(d)
Out[9]: 2

d.groupby('SER').head()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-39f494b2f78d> in <module>()
----> 1 d.groupby('SER').head()

AttributeError: 'pytraj.DataSetList.DataSetList' object has no attribute 'head'

sys.getrefcount(d)
Out[11]: 3

junk = d.groupby('SER'); del junk

sys.getrefcount(d)
Out[13]: 4
```

Notice how the refcount keeps getting incremented.

**Comment by hainm** [comment]
@swails 
> Maybe you're running into a race condition. Does either search_hbonds() or groupby release the GIL? If so, maybe the refcount of the DataSetList is going to zero while groupby("SER") is running and it gets garbage-collected while it's still being used?

> In which case, all you've done is made sure that the result never gets freed...

There is no GIL-related issue here.

this is the behind the scene. search_hbonds() can return different objec depend on `dtype`. For example `search_hbonds(dtype='dataset')` will return DataSetList (cpptraj); `search_hbonds(dtype='ndarray'`) will return raw numpy array. For the default, I used `datataset` as default value since I can use `groupby` to take a subset of data (hbond in cpptraj gives lots of data). 

Whenever calling `groupby("SER")`, a new DataSetList object (called `d_new` in this post) is created and hold a subset of DataSet (from the old DataSetList (called `d_old`) as a view (no copy is made). Since `pytraj` create DataSetList by c++ `new` method, there is `__deallloc__` method to `del` cpptraj's object. But for the `d_new`, I dont let it `del` original data from `d_old` since it just hold a `view`. This is the source of segmentation fault in `traj.search_hbond().groupby("SER")`: because `traj.search_hbond()` will return a DataSetList object, this object is deallocated right away since there is no reference variable to keep it alive. So if calling `groupby` method, there is no cpptraj' DataSetList object anymore. But if we do this 
```python
dslist = traj.search_hbonds()
d0 =dslist.groupby("SER")
```
there is no segfault because I am using `dslist` to keep lifetime of DataSetList. :D 

To avoid segfault for `traj.search_hbond().groupby("SER")`, I just blindly increase reference counter.

> IMO, a leak is only a tiny bit better than a segfault. And in this case, if the "before" syntax avoided both segfaults and leaks, the new behavior might be worse (if it does indeed always result in a leak). H-bond datasets can be huge.

I will keep in mind this and add more assertion to cpptraj test case (that's why I keep asking @mojyt to add more test to Amber for cpptraj so I can make sure that `pytraj` 's results are legit).

btw, you can have a quick look at DataSetList code here for `__deallloc__`, it might be helpful if you want to use `cython` for `ParmEd` in future.
https://github.com/pytraj/pytraj/blob/master/pytraj/DataSetList.pyx#L40

**Comment by hainm** [comment]
per your code example about the leak, I will check. Thanks.

Hai

**Comment by swails** [comment]
This change basically just used `Py_INCREF` to kick the garbage collector out of the way :).  Whatever the bug happens to be, the root cause still exists.  But #410 uses your blind incref to avoid the segfault while still avoiding the memory leak:

```Python
In [1]: from __future__ import print_function
   ...: import unittest
   ...: import sys
   ...: from pytraj.base import *
   ...: from pytraj import adict
   ...: from pytraj import io as mdio
   ...: from pytraj.utils.check_and_assert import assert_almost_equal
   ...: from pytraj.decorators import no_test, test_if_having
   ...: import pytraj.common_actions as pyca
   ...: 

In [2]: traj = mdio.iterload('./data/md1_prod.Tc5b.x', './data/Tc5b.top')

In [3]: d = pyca.search_hbonds(traj)

In [4]: sys.getrefcount(d)
Out[4]: 2

In [5]: junk = d.groupby('SER'); del junk

In [6]: sys.getrefcount(d)
Out[6]: 2

In [7]: e = pyca.search_hbonds(traj).groupby('SER')

In [8]: # Look ma, no segfault!
```

**Comment by swails** [comment]
Actually, I wasn't getting a segfault before this commit with Python 2.7.

**Comment by hainm** [comment]
@swails  there is no segmentation fault anymore since I just increase reference for DataSetList. The main problem here is to have leaking or not. I've try your new change with PY3 but the result is different from yours. Did you use PY2?

```python
In [6]: from pytraj import adict

In [7]: from pytraj import io as mdio

In [8]: from pytraj.utils.check_and_assert import assert_almost_equal

In [9]: from pytraj.decorators import no_test, test_if_having

In [10]: import pytraj.common_actions as pyca


In [11]: traj = mdio.iterload('./data/md1_prod.Tc5b.x', './data/Tc5b.top')

In [12]: d = pyca.search_hbonds(traj)

In [13]: #assert sys.getrefcount(d) == 2

In [14]: sys.getrefcount(d) == 2
Out[14]: True

In [15]: junk = d.groupby('SER'); del junk

In [16]: #assert sys.getrefcount(d) == 2

In [17]: sys.getrefcount(d)
Out[17]: 3

In [18]: e = pyca.search_hbonds(traj).groupby('SER')
```

**Comment by swails** [comment]
That's exactly what I was getting for Python 2 with #408.  The results I showed second (different from yours) were for my PR #410.

**Comment by swails** [comment]
I edited my 2 comments above to indicate where each results came from.  Note that the one that came from this PR gets a refcount of 3 once you call groupby, as you see in your results.  Call it again, and you get a refcount of 4, ... and so on.  With #410, the refcount stays at 2 after calling `groupby`.

**Comment by hainm** [comment]
@swails: yes, I know what you meant. I compile pytraj with #410 but still getting `3` after calling `groupby`. It's weird. Just try both PY2 and PY3 and getting the same result. 

But things are fine now. I just messed up with old `pytraj` version. (I used python setup.py build -faster_build but did not call 'install' later :D). 

Hai

**Comment by swails** [comment]
Ah, gotcha.

**Comment by swails** [comment]
Oh, I misread your first reply.  So you know the root cause of this issue, sorry about that.  I submitted a better PR for this, IMO (see #411).  I don't actually think #410 will work, since your point about the refcount going to zero and getting deallocated still stands.  You really do need a reference since this is a memory view and not a data copy.

So what I did in #411 was add a reference to the "parent" list in a private attribute of the `groupby` set.  This way, when the `groupby` refcount goes to zero, the extra reference to the parent list goes away, too, thereby eliminating the leak.

I didn't add the extra attribute to the pxd file yet (testing it out).  I'm fairly new to Cython, but what do you think of that new approach?

**Comment by swails** [comment]
I feel like numpy must face this all the time.  Do you know what they do?

**Comment by hainm** [comment]
> I didn't add the extra attribute to the pxd file yet (testing it out). I'm fairly new to Cython, but what do you think of that new approach?

It's good for me. I am adding to pxd file now. But I need to re-cythonize all *pyx files that `cimport DataSetList`. If not, we will get some error complaining about wrong size for DataSetList. This is why I barely update "pxd" signature file.

 > I feel like numpy must face this all the time. Do you know what they do?

I don't know any thing about numpy stuff. Its code is too complicated for me. I got the idea to increase reference counting (blindly) when reading this article about numpy in cython. 

https://github.com/cython/cython/wiki/tutorials-numpy

(to save your time, just search for "Keep in mind that the Numpy C API has a strange convention where most entry points which take a "dtype" reference "steal" a reference to the dtype (they Py_DECREF the dtype)"

Hai

**Pull request merged**
