### PR TITLE
Better way to track references?

### PR DESCRIPTION
**Pull request by swails**

### CODE REVIEW

**Comment by swails** [comment]
Example only, I don't think it works, so do something else.

**Comment by swails** [comment]
This doesn't work!  Sorry.

**Comment by hainm** [comment]
@swails what do you mean about 'does not work'? 

your change passed my test case (tested locally). 
https://github.com/hainm/pytraj/commit/0d83ab3e44d00521b7255cd889763030e73c0701

**Comment by swails** [comment]
> @swails what do you mean about 'does not work'?
> 
> your change passed my test case (tested locally).

I can't even get pytraj to import correctly after this change... something about DataSetList being the wrong size.

**Comment by hainm** [comment]
@swails because you update "pxd" signature file. So you need to re-cythonize all *pyx (any files that relates to "cimport DataSetList". 

This is why I made "clean_cythonize_files.py" in the main folder "python clean_cythonize_files.py" to remove all cythonized files. And then "python ./setup.py install" again. 

Because of this reason, I rarely update *pxd* files.

However, I just updated all cythonized codes in pytraj/pytraj. You can pull and try again. It works well for me.

Hai

**Comment by hainm** [comment]
passed travis https://travis-ci.org/hainm/pytraj/jobs/65142682

thanks.

**Pull request merged**
